### =========================================================================
### denyregions metadata
### -------------------------------------------------------------------------
###

meta <- data.frame(
    Title = c("hg38.Meuleman.Cancer_epithelial.rds",
              "hg38.Meuleman.Cardiac.rds",
              "hg38.Meuleman.Digestive.rds",
              "hg38.Meuleman.Lymphoid.rds",
              "hg38.Meuleman.Musculoskeletal.rds",
              "hg38.Meuleman.Myeloid_erythroid.rds",
              "hg38.Meuleman.Neural.rds",
              "hg38.Meuleman.Organ_devel_renal.rds",
              "hg38.Meuleman.Placental_trophoblast.rds",
              "hg38.Meuleman.Primitive_embryonic.rds",
              "hg38.Meuleman.Pulmonary_devel_.rds",
              "hg38.Meuleman.Renal_cancer.rds",
              "hg38.Meuleman.Stromal_A.rds",
              "hg38.Meuleman.Stromal_B.rds",
              "hg38.Meuleman.Tissue_invariant.rds",
              "hg38.Meuleman.Vascular_endothelial.rds"),
    Description = c("DNAse I regions in Cancer / epithelial",
                    "DNAse I regions in Cardiac ",
                    "DNAse I regions in Digestive",
                    "DNAse I regions in Lymphoid",
                    "DNAse I regions in Musculoskeletal",
                    "DNAse I regions in Myeloid / erythroid",
                    "DNAse I regions in Neural",
                    "DNAse I regions in Organ devel. / renal",
                    "DNAse I regions in Placental / trophoblast",
                    "DNAse I regions in Primitive / embryonic",
                    "DNAse I regions in Pulmonary devel.",
                    "DNAse I regions in Renal / cancer",
                    "DNAse I regions in Stromal A",
                    "DNAse I regions in Stromal B",
                    "DNAse I regions in Tissue invariant",
                    "DNAse I regions in Vascular / endothelial"),
    BiocVersion = rep("3.14", 16),
    Genome = c("hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38"),
    SourceType = rep("RDS", 16),
    SourceUrl = rep("https://drive.google.com/drive/folders/14yHnVLZ2XDEOkVufgAyjKJ66Sjmt25eG?usp=sharing", 16),
    SourceVersion = rep("May 30, 2021", 16),
    Species = c(rep("Homo sapiens", 16)),
    TaxonomyId = c(rep(9606, 16)),
    Coordinate_1_based = rep(TRUE, 16),
    DataProvider = c(rep("https://www.meuleman.org/research/dhsindex/", 16)),
    Maintainer = rep("Mikhail Dozmorov <mikhail.dozmorov@gmail.com>", 16),
    RDataClass = rep("GRanges", 16),
    DispatchClass = rep("RDS", 16),
    RDataPath = c("hg38.Meuleman.Cancer_epithelial.rds",
                  "hg38.Meuleman.Cardiac.rds",
                  "hg38.Meuleman.Digestive.rds",
                  "hg38.Meuleman.Lymphoid.rds",
                  "hg38.Meuleman.Musculoskeletal.rds",
                  "hg38.Meuleman.Myeloid_erythroid.rds",
                  "hg38.Meuleman.Neural.rds",
                  "hg38.Meuleman.Organ_devel_renal.rds",
                  "hg38.Meuleman.Placental_trophoblast.rds",
                  "hg38.Meuleman.Primitive_embryonic.rds",
                  "hg38.Meuleman.Pulmonary_devel_.rds",
                  "hg38.Meuleman.Renal_cancer.rds",
                  "hg38.Meuleman.Stromal_A.rds",
                  "hg38.Meuleman.Stromal_B.rds",
                  "hg38.Meuleman.Tissue_invariant.rds",
                  "hg38.Meuleman.Vascular_endothelial.rds"),
    Tags = c("DNAse;Cancer;epithelial",
             "DNAse;Cardiac ",
             "DNAse;Digestive",
             "DNAse;Lymphoid",
             "DNAse;Musculoskeletal",
             "DNAse;Myeloid;erythroid",
             "DNAse;Neural",
             "DNAse;Organ devel.;renal",
             "DNAse;Placental;trophoblast",
             "DNAse;Primitive;embryonic",
             "DNAse;Pulmonary devel.",
             "DNAse;Renal;cancer",
             "DNAse;Stromal A",
             "DNAse;Stromal B",
             "DNAse;Tissue invariant",
             "DNAse;Vascular;endothelial"),
    Notes = "")

write.csv(meta, file="inst/extdata/metadata.csv", row.names=FALSE)
